

== Dependencies

=== Required References

The following referenced documents are indispensable for the application of this document. 
For dated references, only the edition cited applies. For undated references, 
the latest edition of the referenced document (including any amendments) applies:

[#rfc-dom]
    * *DOM 4* specification  : *"W3C DOM 4"* http://www.w3.org/TR/dom/ 
    
[#rfc-uri]
    * *URI* specification : *RFC 3986 - "Uniform Resource Identifier (URI): Generic Syntax"* - http://tools.ietf.org/html/rfc3986 

[#rfc-keywords]
    * Keywords ("must", "shall") specification: *RFC 2119 - "Key words for use in RFCs to Indicate Requirement Levels"* - http://www.ietf.org/rfc/rfc2119.txt 
    
[#rfc-email]
    * Email formatting specifications: 
    ** *RFC 3696* - "Application Techniques for Checking and Transformation of Names" -  http://tools.ietf.org/html/rfc3696
    *** Errata: http://www.rfc-editor.org/errata_search.php?rfc=3696
    ** *RFC 5321* - "Simple Mail Transfer Protocol" - http://tools.ietf.org/html/rfc5321
    ** *RFC 5322* - "Internet Message Format" - http://tools.ietf.org/html/rfc5322

=== Optional References
    
The following referenced documents are indispensable for the understanding of the examples of this document:

[#rfc-xml]
    * *XML* specification : "Extensible Markup Language (XML) 1.0 (Fifth Edition)" - http://www.w3.org/TR/2008/REC-xml-20081126/
[#rfc-xsd]
    * *XSD* specification: 
    ** "XML Schema Part 0: Primer Second Edition" - http://www.w3.org/TR/xmlschema-0/
    ** "XML Schema Part 1: Structures Second Edition" - http://www.w3.org/TR/xmlschema-1/
    ** "XML Schema Part 2: Datatypes Second Edition" - http://www.w3.org/TR/xmlschema-2/
    
=== References Usage
    
. The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", 
"MAY", and "OPTIONAL" in this document are to be interpreted as described in <<rfc-keywords,RFC 2119>>.

. The AOSL format specifies requirement applied on data organized following the DOM Node Tree structure. 
AOSL data must be organized following the DOM Node Tree structure and must additionally follow 
the AOSL-specific requirements to be conformant.

. This specification expose data using XML schemes in examples. 
AOSL can be encoded within other data formats like JSON, YAML or BSON, but in this document we will exclusively use XML. 
XML helps clarify what is the type of which element of the DOM structure, which help documentation.
In the examples of this document using XML, we will assume (if not specified) that the XML code is extracted 
from a fictive document, which have the following root element definition (englobing the example code):
+
[source,xml]
----
<?xml version="1.0" encoding="utf-8" ?>

<sequence xmlns="artofsequence.org/aosl/1.0" ... " >

    <!-- Example Here -->

</sequence>
----
+
As specified in this XML sample, the XML namespace used is implicitely the AOSL XML namespace. 
This imply that all tags specific to AOSL are not prefixed in the examples.
    
. An XSD scheme file enforcing this specification for XML data is provided at http://artofsequence.org/aosl/1.0 
It can be used by tools to check the validity of AOSL data as XML.
In the examples of this document using XSD, we will assume (if not specified) that the XSD code is extracted 
from this XSD document, which have the following root element definition (englobing the example code):
+
[source,xml]
----
<xs:schema xmlns:aos="artofsequence.org/aosl/1.0"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            attributeFormDefault="unqualified"
            elementFormDefault="qualified"
            targetNamespace="artofsequence.org/aosl/1.0"
            version="1.0"
            >
    
    <!-- Example Here -->

</xs:schema>
----
+
As specified in this XSD sample, *aos* is the XML namespace used for xml tags specific AOSL.

