

== General

=== Scope

. **This document specifies the version 1.0 Art Of Sequence Language (AOSL) format.** 

. AOSL is a universal format for representing narratives implemented using digital plateforms. 
It's purpose is to be a bridge between tools (for authors, publishers and developers), 
interpreters (also called "players") in a variety of ways. It can also be used directly by 
an interpreter to read a narrative.

. The implementations following this specification are able to read, 
interpret and modify AOSL documents in an inter-operable way, 
which means that AOSL data read, interpreted and modified by one implementation can be read, 
interpreted and modified by another as long as both implementation apply the requirements of this document. 
Such implementations are called confirming implementations.
Therefore, the first requirement is to implement this specification.

=== Status of This Document

This is a working draft of the specification.


=== Concept Overview

. The AOSL format is designed to describe a narrative implemented using digital platforms 
**in a universal way**. 

. One important pillar concept of how AOSL is structured is that any narrative can be reduced to a sequence of information,
which takes the form of a sequence of changes applied to an initial state. 
In this description of narrative, there is no time-related specification. Therefore, **AOSL describe narratives 
in a way that avoid specifying time constraints.** Videos and other time-constrained narratives are structured differently 
but AOSL takes the more general direction of asking from the author to specify changes in sequential order instead
of asking time information about when to apply these changes.

. To allow the full exploitation of the digital platform capabilities, **AOSL describes to the interpreter
how to build the sequence of changes to be applied through the reading of the narrative**.
This mean that instead of specifying "where should be what" at each stage of the narration (like most
similar formats does), it actually specify "how to figure out where should be what" at each stage of the narration.
This level of indirection allows the authors of the narratives to introduce decision making and other 
possibilities, if they want to, without having to learn a programming language or add a programmer to the author team.

. **This procedurality is allowed by describing the narrative as a sequence of changes applied to an initial state.
That sequence of changes is generated by the path taken in a graph of changes (transitions).**
Therefore, the path taken by the interpreter in the narrative (either chosen by the reader or imposed, or even randomized)
determine the perceived sequence generated by the interpreter.

. Another important distinction from other more descriptive formats is that AOSL does not impose 
constraints on resource formats (like images, audio or video formats): **AOSL is media-agnostic by design**. 
An implementation of an interpreter will have such constraints, that it should expose to the edition tools
so that authors can only work with an AOSL file under theses specific constraints.
However, AOSL itself don't impose such constraints and therefore could describe any kind of resource usage.
For a pragmatic use, AOSL should always be used in combination with either a more constraint 
specification (like [XAOSL]) or a specification of constraints specific an interpreter implementation.

. AOSL is also designed following the ["open-closed principle"] which basically states that an extensible system 
should be "closed" with a specific interface exposing "extension points" so that extensions can be controlled in the 
frame of the system described. **AOSL specify several extension points which allow experimentations and implementation-specific
enhancements to be provided to users.** If the interpreter can't interpret data in one of these extension, it can be ignored.
Therefore, it is possible for a specific tool-chain to add several new features over the AOSL basics, but still allow 
implementations that can't read these specific features to still read the AOSL basic data.

. For more details on the design of AOSL, see [AOSL: Design Guidelines].


